#
# REGISTRY: ~/.bash_profile
#
# This file ensures that ~/.bashrc is loaded for login shells. It serves as the
# entry point for creating an interactive shell session.
#

#
# IMPLEMENTATION
#

# --- Source the main bashrc for interactive settings ---
if [ -n "$BASH_VERSION" ]; then
    if [ -f "$HOME/.bashrc" ]; then
        source "$HOME/.bashrc"
    fi
fi
. "$HOME/.cargo/env"
